INSERT INTO users (name, age) VALUES ("Brenda", 45)
INSERT INTO users (name, age) VALUES ("Josh", 19)
INSERT INTO users (name, age) VALUES ("Samuel", 63)
INSERT INTO users (name, age) VALUES ("Catherine", 47)
INSERT INTO users (name, age) VALUES ("Victoria", 62)
INSERT INTO users (name, age) VALUES ("George", 23)
INSERT INTO users (name, age) VALUES ("Geoff", 37)
INSERT INTO users (name, age) VALUES ("Erin", 32)
INSERT INTO users (name, age) VALUES ("Cara", 36)
INSERT INTO users (name, age) VALUES ("Kerstin", 28)
INSERT INTO users (name, age) VALUES ("David", 30)
INSERT INTO users (name, age) VALUES ("Hannah", 27)
INSERT INTO users (name, age) VALUES ("Jane", 40)
INSERT INTO users (name, age) VALUES ("Jordan", 16)
INSERT INTO users (name, age) VALUES ("Byron", 34)
INSERT INTO users (name, age) VALUES ("Anita", 26)
INSERT INTO users (name, age) VALUES ("Carol", 60)
INSERT INTO users (name, age) VALUES ("Josie", 54)
INSERT INTO users (name, age) VALUES ("Mike", 63)
INSERT INTO users (name, age) VALUES ("Sue", 63)

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dogpatch Urban Gardens", "Farms", 15000, "February 25", "March 25" )
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Buildthemill Continues- Restoring Tartan", "Weaving", 55202, "February 9","March 9")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gruff: Mutant Goat Enamel Pins", "Accessories", 500, "February 9","March 9")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("BRINS Jam & Marmalade Relaunch! (Formerly known as STAGG)", "Small Batch", 6000, "February 22", "March 22")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Kitsune, Japanese restaurant in Williamsburg, Brooklyn", "Restaurants", 90000, "February 19", "March 19")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Study Woodworking in Japan!", "Woodworking", 28368, "February 15", "March 15")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("CEYLOVE: From Sri Lanka With Spice", "Food", 2500, "February 16", "March 16")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Primal Supply Meats Butcher Shop", "Spaces", 3500, "February 4", "March 4")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ARAMLEE | Convertible Leather Handbags", "Accessories", 20000, "February 22", "March 22")
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Orbasics - a better way to dress your kids", "Childrenswear", 18477, "February 16", "March 16")


INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
INSERT INTO pledges (amount, user_id, project_id) VALUES ()
