INSERT INTO users (name, age) VALUES ("Brenda", 45);
INSERT INTO users (name, age) VALUES ("Josh", 19);
INSERT INTO users (name, age) VALUES ("Samuel", 63);
INSERT INTO users (name, age) VALUES ("Catherine", 47);
INSERT INTO users (name, age) VALUES ("Victoria", 62);
INSERT INTO users (name, age) VALUES ("George", 23);
INSERT INTO users (name, age) VALUES ("Geoff", 37);
INSERT INTO users (name, age) VALUES ("Erin", 32);
INSERT INTO users (name, age) VALUES ("Cara", 36);
INSERT INTO users (name, age) VALUES ("Kerstin", 28);
INSERT INTO users (name, age) VALUES ("David", 30);
INSERT INTO users (name, age) VALUES ("Hannah", 27);
INSERT INTO users (name, age) VALUES ("Jane", 40);
INSERT INTO users (name, age) VALUES ("Jordan", 16);
INSERT INTO users (name, age) VALUES ("Byron", 34);
INSERT INTO users (name, age) VALUES ("Anita", 26);
INSERT INTO users (name, age) VALUES ("Carol", 60);
INSERT INTO users (name, age) VALUES ("Josie", 54);
INSERT INTO users (name, age) VALUES ("Mike", 63);
INSERT INTO users (name, age) VALUES ("Sue", 63);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dogpatch Urban Gardens", "Farms", 15000, "February 25", "March 25" );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Buildthemill Continues- Restoring Tartan", "Weaving", 55202, "February 9","March 9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Gruff: Mutant Goat Enamel Pins", "Accessories", 500, "February 9","March 9");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("BRINS Jam & Marmalade Relaunch! (Formerly known as STAGG)", "Small Batch", 6000, "February 22", "March 22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Kitsune, Japanese restaurant in Williamsburg, Brooklyn", "Restaurants", 90000, "February 19", "March 19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Study Woodworking in Japan!", "Woodworking", 28368, "February 15", "March 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("CEYLOVE: From Sri Lanka With Spice", "Food", 2500, "February 16", "March 16");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Primal Supply Meats Butcher Shop", "Spaces", 3500, "February 4", "March 4");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ARAMLEE | Convertible Leather Handbags", "Accessories", 20000, "February 22", "March 22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Orbasics - a better way to dress your kids", "Childrenswear", 18477, "February 16", "March 16");


INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (164, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (195, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (187, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (345, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (674, 11, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (112, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (905, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (932, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (673, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (892, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (650, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (703, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (654, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (873, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3672, 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (340, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (643, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (880, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (640, 11, 9);
